// Imports
const $FlintAndSteelItem = Java.loadClass('net.minecraft.world.item.FlintAndSteelItem')
const $ItemProperties = Java.loadClass('net.minecraft.world.item.Item$Properties')

global.tfcWoodTypes = [
    'acacia',
    'ash',
    'aspen',
    'birch',
    'blackwood',
    'chestnut',
    'douglas_fir',
    'hickory',
    'kapok',
    'mangroove',
    'maple',
    'oak',
    'palm',
    'pine',
    'rosewood',
    'sequoia',
    'spruce',
    'sycamore',
    'white_cedar',
    'willow'
]
global.afcWoodTypes = [
    'baobab',
    'eucalyptus',
    'mahogany',
    'hevea',
    'tualang',
    'teak',
    'cypress',
    'fig',
    'ironwood',
    'ipe'
]
global.afcWoodTypesExtra = [
    'rainbow_eucalyptus',
    'redcedar',
    'gum_arabic',
    'black_oak',
    'poplar',
    'rubber_fig'
]
global.tfcRockTypes = [
    'granite',
    'diorite',
    'gabbro',
    'shale',
    'conglomerate',
    'claystone',
    'limestone',
    'dolomite',
    'chert',
    'chalk',
    'ryhollite',
    'basalt',
    'andesite',
    'dacite',
    'quartzite',
    'slate',
    'phyllite',
    'schist',
    'gneiss',
    'marble',
]
global.grainTypes = [
    'wheat',
    'barley',
    'oat',
    'rye',
    'corn',
    'maize',
    'rice',
]
global.dyes = [
    'white',
    'orange',
    'magenta',
    'light_blue',
    'yellow',
    'lime',
    'pink',
    'gray',
    'light_gray',
    'cyan',
    'purple',
    'blue',
    'brown',
    'green',
    'red',
    'black'
]
global.TFCMetals = [
    'bismuth',
	'gold',
	'silver',
	'nickel',
	'tin',
	'zinc',
	'cast_iron',
	'brass',
	'rose_gold',
	'sterling_silver',
	'copper',
	'bronze',
	'bismuth_bronze',
	'black_bronze',
	'wrought_iron',
	'steel',
	'black_steel',
	'blue_steel',
	'red_steel',
]
global.FLMetals = [
    'chromium',
    'stainless_steel'
]
global.MMetal = [
    'copper',
	'bronze',
	'bismuth_bronze',
	'black_bronze',
	'wrought_iron',
	'steel',
	'black_steel',
	'blue_steel',
	'red_steel',
]

const MMetalDurability = {
    'copper': 600,
	'bronze': 1300,
	'bismuth_bronze': 1200,
	'black_bronze': 1460,
	'wrought_iron': 2200,
	'steel': 3300
}


global.tfcRockCatergories =[
    'igneous_extrusive',
    'igneous_intrusive',
    'metamorphic',
    'sedimentary'
]

global.tfcOreTypes = {
    'bismuthinite': 270,
    'cassiterite': 230,
    'garnierite': 1453,
    'hematite': 1535,
    'limonite': 1535,
    'magnetite': 1535,
    'malachite': 1080,
    'native_copper': 1080,
    'native_gold': 1060,
    'native_silver': 961,
    'sphalerite': 420,
    'tetrahidrite' : 1080,
}

global.disabledItems = [
    /astikorcarts:.*/,
    /afc:(?:birch|maple)_sugar/,
    'afc:rubber_bar',
    /afc:bucket\/.*/,
    /tfc:wood\/boat.*/,
    /afc:wood\/boat.*/,
    /firmalife:(?:cinnamon)/,
    /firmaciv:.*(barometer|sextant|nav_clock)/,
    'firmaciv:sextant',
    'firmalife:tirage_mixture',
    'firmalife:seed_ball',
    /tfc:ceramic\/(:?saw|chisel|scythe).*_mold/,
    /tfc:wood\/(?:sewing).*/,
    /afc:wood\/(?:sewing).*/,
    /tfcscraping:ceramic\/.*/,
    /tfc:food\/.*(:?bear).*/,
    /cold_sweat:(:?holgin|goar|chameleon|soul).*/,
    /tfchotornot:.*\/(:?zinc|gold|silver|sterling_silver|tin|rose_gold|nickel)/,
    'tfchotornot:tongs/bismuth',
    'tfchotornot:tong_part/bismuth',
    /rnr:.*(:?pouring|wet|cracked|trodden).*/,
    /^precisionprospecting:ceramic\/.*/,
    /supplementaries:.*(:?lumisene|candle|sconce|lamp|flint|feather|sugar|fodder|gold|netherite|fine).*/,
    /supplementaries:.*(:?lapis|stone|gravel|daub|timber|flax).*/,
    /supplementaries:(:?sign_post).*/,
    /alekiroofs:(:?oak|spruce|jungle|birch|mangrove|acacia|cherry|warped|crimson|bamboo|dark)_.*/
]
global.extraSupplementariesDisabled = [
    'soap_block', 'fire_pit', 'lunch_basket', 'quiver', 'speaker_block',
    'goblet', 'altimeter', 'flower_box', 'planter', 'urn', 'jar', 'sack',
    'bamboo_spikes_tipped', 'enderman_head', 'cog_block', 'crank',
    'cannon', 'faucet', 'relayer', 'display', 'bellows', 'dispener_minecart',
    'redstone_illuminator', 'slice_map', 'bomb_blue', 'cannon_ball',
    'pancake', 'candy', 'ash_brick', 'ash',
]
global.disabledFluids = [
    'afc:birch_sap_concentrate',
    'afc:maple_sap_concentrate',
    'afc:latex',
    'firmalife:fruity_fluid', 
    'rnr:concrete',
    'supplementaries:lumisene'
]
global.vanillaDisabled = [
    /minecraft:.*(?:oak|spruce|birch|dark_oak|cherry|jungle|acacia|mangrove|crimson|warped).*/,
    /minecraft:.*(?:andesite|cobblestone|granite|deepslate|blackstone|diorite|quartz|basalt|calcite|tuff|amethyst|magma|end|debris|obsidian|soul|prismarine|sand|sandstone|mud|moss|chiseled|polished|infested|smooth|end_stone|purpur|nether|concrete).*/,
    /minecraft:.*(?:iron|diamond|gold|chainmail|copper|stone|wooden|emerald|lapis|netherite|end|bucket|horn|tipped).*/,
    /minecraft:.*(bucket|tipped|candle).*/,
    'minecraft:trident',
    'minecraft:shears',
    'minecraft:elytra',
    'minecraft:turtle_helmet',
    'minecraft:totem_of_undying',
    'minecraft:spectral_arrow',
    /minecraft:redstone.*/,
    /minecraft:.*(?:_rail|_button|_pressure_plate)/,
    'minecraft:observer',
    'minecraft:repeater',
    'minecraft:comparator',
    'minecraft:lever',
    'minecraft:target',
    'minecraft:torch',
    'minecraft:hopper',
    'minecraft:dispenser',
    'minecraft:dropper',
    'minecraft:bell',
    /minecraft:.*(:?chest|anvil|minecart|piston|tnt|furnace).*/,
    'minecraft:barrel',
    'minecraft:bookshelf',
    'minecraft:lecturn',
    'minecraft:tripwire_hook',
    /minecraft:.*(?:tulip|bush|flower|daisy|lilac|vine|rose|plant|coral|driplea|azalea).*/,
    'minecraft:fern',
    'minecraft:large_fern',
    'minecraft:dandelion',
    'minecraft:poppy',
    'minecraft:blue_orchid',
    'minecraft:allium',
    'minecraft:azure_bluet',
    'minecraft:lily_of_the_valley',
    'minecraft:pink_petals',
    'minecraft:sugar_cane',
    'minecraft:cactus',
    'minecraft:peony',
    'minecraft:glow_lichen',
    'minecraft:hanging_roots',
    'minecraft:lily_pad',
    'minecraft:spore_blossom',
    /minecraft:.*(?:mutton|beef|chicken|pumpkin|beetroot|egg|rabbit|pork|potato|wheat|carrot|melon|kelp|fish|salmon|cod|cookie|bread|cake|stew|berries|cocoa|bee).*/,
    'minecraft:apple',
    /minecraft:.*(?:skull|head|sculk|sponge|shulker|lantern|potion|enchant|blaze)/,
    'minecraft:grindstone',
    'minecraft:smoker',
    'minecraft:brewing_stand',
    'minecraft:campfire',
    'minecraft:composter',
    'minecraft:conduit',
    'minecraft:beacon',
    'minecraft:spawner',
    'minecraft:respawn_anchor',
    'minecraft:decorated_pot',
    /minecraft:bamboo_.*(?:sign|raft)/,
    'minecraft:cauldron',
    'minecraft:hay_block',
    /minecraft:(honey|slime|coal).*/,
    'minecraft:fire_charge',
    'minecraft:glass_bottle',
    'minecraft:dragon_breath',
    'minecraft:fermented_spider_eye',
    'minecraft:ghast_tear',
    'minecraft:phantom_membrane',
    'minecraft:experience_bottle',
    'minecraft:nautilus_shell',
    'minecraft:echo_shard',
    'minecraft:disc_fragment_5',
    'minecraft:heart_of_the_sea',
    /minecraft:.*(?:podzol|mycelium|dirt|farmland|gravel|grass|shroom|froglight|chorus).*/,
    'minecraft:chain',
    'minecraft:spawner',
    'minecraft:observer',
    'minecraft:rail',
    'minecraft:recovery_compass',
    'minecraft:compass',
    'minecraft:pitcher_pod',
    'minecraft:sea_pickle',
    'minecraft:frog_spawn',
    /minecraft:bamboo_(;?planks|mosaic|stairs|slab|fence|door|trapdoor).*/
]