#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

#Disables specific entries
[entries]

		[entries.wood_type.valhelsia_structures]
			bundled_stripped_posts = true
			stripped_post = false
			cut_post = false
			bundled_posts = true
			post = false
			cut_stripped_post = false

		[entries.wood_type.another_furniture]
			table = true
			flower_box = true
			shelf = true
			drawer = false
			shutter = false
			bench = true
			chair = true
