#
# Maximum (hidden) nutrition that players can have going above 100%, making it easier to reach 100% average nutrition
# Default: 1.1
# Range: 1.0 ~ 3.4028234663852886E38
maximum_nutrition = 1.1
#
# Whether the decay of nutrients is proportional to the amount of nutrients a player has. Otherwise, it will just be a constant decay rate
proportional_nutrition_decay = true
#
# The minimum proportion of the nutrition decay rate that is applied, if proportional nutrition decay is enabled.
# This is basically the amount of nutrients a meal must provide to maintain a stable level of player nutrition intake / outflow
# Default: 0.75
# Range: 0.0 ~ 1.0
proportional_decay_floor = 0.75
#
# Force player decay rates to be equal to the custom decay rates set in the config, recommended if you want to change decay rates on a public server.
# This will go into effect once a player joins the world / server, and will override decay rates set via command!
force_custom_decay_rates = false
#
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
default_grain_decay_rate = 1.0
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
default_fruit_decay_rate = 1.0
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
default_vegetables_decay_rate = 1.0
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
default_protein_decay_rate = 1.0
# Default: 1.0
# Range: 0.0 ~ 3.4028234663852886E38
default_dairy_decay_rate = 1.0
#
# The remaining percentage of nutrition a player keeps after dying, if the TFC config `keepNutritionAfterDeath` is disabled.
# At `0` this will remove all nutrients from a player, while at `1` it won't change the nutrients at all
# Default: 0.9
# Range: 0.0 ~ 1.0
nutrition_modifier_on_death = 0.9
