[search_and_range]
	#Max range to search for blocks from player entities
	# Default: 32
	# Range: 8 ~ 64
	searchRange = 32
	#Max range to search for blocks from animal entities
	# Default: 16
	# Range: 4 ~ 32
	isMobSearchRange = 16
	#Number of blocks above to be considered underground
	# Default: 24576
	# Range: 8192 ~ 65536
	maxBlocksAbove = 24576
	#Maximum blocks to check for fluid depth temp modifier
	# Default: 32
	# Range: 8 ~ 64
	maxFluidDepthCheck = 32
	#Maximum volume or number of blocks an interior can have
	# Default: 13824
	# Range: 4096 ~ 32768
	maxInteriorVolume = 13824

[entity_temperature]
	#Maximum heat by nearby sources
	# Default: 75
	# Range: 50 ~ 150
	maxRadiantHeating = 75
	#Maximum heating from hot TFC items in inventory
	# Default: 75
	# Range: 50 ~ 150
	maxInventoryHeating = 75
	#Percentage used for various calculations that use buffers or segments
	# Default: 15
	# Range: 0 ~ 50
	temperatureSegmentsPercent = 15
	#Maximum amount of hyper/hypothermia effect levels.
	# Default: 4
	# Range: 2 ~ 8
	maxTemperatureEffectLevel = 4
	#Hydration loss through sweat multiplier
	# Default: 1.0
	# Range: 0.0 ~ 2.0
	playerSweatHydrationLossMulti = 1.0
	#Inventory heat multiplier
	# Default: 1.0
	# Range: 0.0 ~ 2.0
	inventoryHeatMulti = 1.0
	#Entity temperature change multiplier
	# Default: 0.5
	# Range: 0.1 ~ 2.0
	entityTemperatureChangeMulti = 0.5
	#Entity climate acclimatisation multiplier
	# Default: 1.0
	# Range: 0.1 ~ 2.0
	entityAcclimatisationMulti = 1.0

[ai_and_memory]
	#Number of days animal remembers warm and cold locations
	# Default: 7
	# Range: 1 ~ 96
	memoryDecayDays = 7
	#Maximum time (in TFC minutes) an animal will stay at a comfortable location
	# Default: 120
	# Range: 5 ~ 480
	maxStayTimeMinutes = 120

[environment_temperature]
	#Max heating applied by sun
	# Default: 32.0
	# Range: 0.0 ~ 48.0
	maxSolarHeating = 32.0
	#Evaporative cooling multiplier
	# Default: 1.0
	# Range: 0.0 ~ 2.0
	evapCoolingMulti = 1.0
	#Solar radiation multiplier
	# Default: 1.0
	# Range: 0.0 ~ 2.0
	solarRadiationMulti = 1.0
	#Drying multiplier
	# Default: 1.0
	# Range: 0.0 ~ 2.0
	dryingMulti = 1.0
	#Interior source pull multiplier
	# Default: 1.0
	# Range: 0.5 ~ 10.0
	interiorSourceMulti = 1.0

[server_misc]
	#Disable TFC's temperature dependant thirst.
	overrideTFCTempThirst = true
