[creativeModeTabs]
	enableCreativeModeTabs = false
	syncSelectedCreativeModeTab = true
	showCreativeTabNameInSearchbar = true
	disabledCreativeModeTabs = ["minecraft:op_blocks"]

[stackGroups]
	enableStackGroups = false
	enableCreateStackGroupButton = false

[miscellaneous]
	emiOnlyInRecipeBook = false
